#!/usr/bin/with-contenv sh
set -e

set_listen_addresses() {
	sedEscapedValue="$(echo "$1" | sed 's/[\/&]/\\&/g')"
	sed -ri "s/^#?(listen_addresses\s*=\s*)\S+/\1'$sedEscapedValue'/" "$PGDATA/postgresql.conf"
}

mkdir -p "$PGDATA"
chown -R postgres "$PGDATA"

chmod g+s /run/postgresql
chown -R postgres /run/postgresql

POSTGRES_LOGS_FIFO=/var/run/s6/postgres-logs-fifo
if [ ! -p $POSTGRES_LOGS_FIFO ]; then
    mkfifo -m 0600 $POSTGRES_LOGS_FIFO 
    chown postgres:postgres $POSTGRES_LOGS_FIFO
fi

# look specifically for PG_VERSION, as it is expected in the DB dir
if [ ! -s "$PGDATA/PG_VERSION" ]; then
    su postgres -c /usr/lib/postgresql/"$PG_MAJOR"/bin/initdb

    # check password first so we can output the warning before postgres messes it up
    if [ "$POSTGRES_PASSWORD" ]; then
        pass="PASSWORD '$POSTGRES_PASSWORD'"
        authMethod=md5
    else
    #WARNING GOES HERE SOMEHOW
        pass=
        authMethod=trust
    fi

    { echo; echo "host all all 0.0.0.0/0 $authMethod"; } >> "$PGDATA/pg_hba.conf"

    # internal start of server in order to allow set-up using psql-client       
    # does not listen on TCP/IP and waits until start finishes
    su postgres -c "/usr/lib/postgresql/"$PG_MAJOR"/bin/pg_ctl -D \"$PGDATA\" \
        -o \"-c listen_addresses=''\" \
        -w start"

    : ${POSTGRES_USER:=postgres}
    : ${POSTGRES_DB:=$POSTGRES_USER}
    export POSTGRES_USER POSTGRES_DB

    if [ "$POSTGRES_DB" != 'postgres' ]; then
        /usr/lib/postgresql/"$PG_MAJOR"/bin/psql --username postgres "CREATE DATABASE \"$POSTGRES_DB\" ;"
    fi

    /usr/lib/postgresql/"$PG_MAJOR"/bin/psql --username postgres -d "$POSTGRES_DB" -c "CREATE EXTENSION adminpack;"

    if [ "$POSTGRES_USER" = 'postgres' ]; then
        op='ALTER'
    else
        op='CREATE'
    fi

    /usr/lib/postgresql/"$PG_MAJOR"/bin/psql -U postgres -d postgres -c "$op USER \"$POSTGRES_USER\" WITH SUPERUSER $pass ;"

#   for f in /docker-entrypoint-initdb.d/*; do
#       case "$f" in
#           *.sh)  echo "$0: running $f"; . "$f" ;;
#           *.sql) echo "$0: running $f"; psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" < "$f" && echo ;;
#           *)     echo "$0: ignoring $f" ;;
#       esac
#   done

    su postgres -c "/usr/lib/postgresql/"$PG_MAJOR"/bin/pg_ctl -D \"$PGDATA\" -m fast -w stop"
    set_listen_addresses '*'

    echo
    echo 'PostgreSQL init process complete; ready for start up.'
    echo

fi

